name: Cypress Tests

on: [push, pull_request]

jobs:
  testing-suite:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies for client
        run: |
          cd ./client
          npm ci

      - name: Install dependencies for server
        run: |
          cd ./server
          npm ci

      - name: Install dependencies for database
        run: |
          cd ./database
          npm ci

      - name: Initialize database
        run: |
          cd ./database
          node initializeDB.js
          sleep 5

      - name: Start server
        run: |
          cd ./server
          npm start &
          sleep 5

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:3000"
          start: npm start
          working-directory: ./client
