name: Cypress Tests

on: [push, pull_request]

jobs:
  testing-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies for client
        working-directory: ./client
        run: npm ci

      - name: Install dependencies for server
        working-directory: ./server
        run: npm ci

      - name: Install dependencies for database
        working-directory: ./database
        run: npm ci

      - name: Start database
        working-directory: ./database
        run: |
          npm start &
          sleep 5

      - name: Start server
        working-directory: ./server
        run: |
          npm start &
          sleep 5

      - name: Run Cypress tests
        working-directory: ./client
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:3000"
          start: npm start
