name: Cypress Tests w/Dependency & Artifacts

on: [push, pull_request]

jobs:
  testing-suite:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Run
        uses: cypress-io/github-action@v6
